/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VisualSummaryWithBreakdown {
    categories: Array<CategorySummary>;
    title: string;
    imagePath: string;
    totalToReceive: bigint;
    categoryBreakdown: Array<CategoryBreakdown>;
    expenses: bigint;
    message: string;
    categoryBreakdownText: string;
    netBalance: bigint;
    subtitle: string;
    entryTypes: Array<EntryTypeSummary>;
}
export interface CategoryBreakdown {
    categoryName: string;
    tripCount: bigint;
}
export interface TripRecord {
    id: string;
    categoryId: string;
    date: bigint;
    amount: bigint;
}
export interface CategorySummary {
    categoryId: string;
    categoryName: string;
    totalAmount: bigint;
    tripCount: bigint;
}
export interface TripCategory {
    id: string;
    name: string;
    defaultAmount: bigint;
}
export interface OtrosEntry {
    id: string;
    entryType: string;
    date: bigint;
    description: string;
    amount: bigint;
}
export interface MonthlySummary {
    month: bigint;
    totalToReceive: bigint;
    userId: string;
    expenses: bigint;
    timestamp: bigint;
    netBalance: bigint;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface MonthlyBreakdown {
    totalTrips: bigint;
    categorySummaries: Array<CategorySummary>;
    entryTypeSummaries: Array<EntryTypeSummary>;
    totalExpenses: bigint;
    totalExtras: bigint;
    netBalance: bigint;
}
export interface UserProfile {
    salary: bigint;
    name: string;
    language: string;
    currency: string;
    companyName: string;
    monthlyGoal: bigint;
}
export interface EntryTypeSummary {
    entryType: string;
    count: bigint;
    totalAmount: bigint;
}
export interface backendInterface {
    addOtrosEntry(userId: string, description: string, amount: bigint, date: bigint, entryType: string): Promise<string>;
    addPositivePhrase(phrase: string): Promise<void>;
    addTripCategory(userId: string, name: string, defaultAmount: bigint): Promise<string>;
    addTripRecord(userId: string, categoryId: string, amount: bigint, date: bigint): Promise<string>;
    createUserProfile(userId: string, name: string, companyName: string, salary: bigint, language: string, monthlyGoal: bigint): Promise<void>;
    deleteOtrosEntry(entryId: string): Promise<void>;
    deleteTripCategory(categoryId: string): Promise<void>;
    deleteTripRecord(recordId: string): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    exportVisualSummary(userId: string, month: bigint): Promise<VisualSummaryWithBreakdown>;
    generateVisualSummary(userId: string, month: bigint): Promise<VisualSummaryWithBreakdown>;
    getAllPositivePhrases(): Promise<Array<string>>;
    getFileReference(path: string): Promise<FileReference>;
    getMonthlyBreakdown(userId: string, month: bigint): Promise<MonthlyBreakdown>;
    getMonthlySummary(userId: string, month: bigint): Promise<MonthlySummary | null>;
    getOtrosEntries(userId: string): Promise<Array<OtrosEntry>>;
    getRandomPositivePhrase(): Promise<string>;
    getTripCategories(userId: string): Promise<Array<TripCategory>>;
    getTripRecords(userId: string): Promise<Array<TripRecord>>;
    getUserProfile(userId: string): Promise<UserProfile | null>;
    listFileReferences(): Promise<Array<FileReference>>;
    registerFileReference(path: string, hash: string): Promise<void>;
    saveMonthlySummary(userId: string, month: bigint, totalToReceive: bigint, expenses: bigint, netBalance: bigint): Promise<void>;
    updateOtrosEntry(entryId: string, description: string, amount: bigint, date: bigint, entryType: string): Promise<void>;
    updateTripCategory(categoryId: string, name: string, defaultAmount: bigint): Promise<void>;
    updateTripRecord(recordId: string, categoryId: string, amount: bigint, date: bigint): Promise<void>;
    updateUserProfile(userId: string, name: string, companyName: string, salary: bigint, language: string, monthlyGoal: bigint): Promise<void>;
}
import type { MonthlySummary as _MonthlySummary, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOtrosEntry(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addOtrosEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOtrosEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addPositivePhrase(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPositivePhrase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPositivePhrase(arg0);
            return result;
        }
    }
    async addTripCategory(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTripCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTripCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async addTripRecord(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTripRecord(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTripRecord(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createUserProfile(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteOtrosEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOtrosEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOtrosEntry(arg0);
            return result;
        }
    }
    async deleteTripCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTripCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTripCategory(arg0);
            return result;
        }
    }
    async deleteTripRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTripRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTripRecord(arg0);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async exportVisualSummary(arg0: string, arg1: bigint): Promise<VisualSummaryWithBreakdown> {
        if (this.processError) {
            try {
                const result = await this.actor.exportVisualSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportVisualSummary(arg0, arg1);
            return result;
        }
    }
    async generateVisualSummary(arg0: string, arg1: bigint): Promise<VisualSummaryWithBreakdown> {
        if (this.processError) {
            try {
                const result = await this.actor.generateVisualSummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateVisualSummary(arg0, arg1);
            return result;
        }
    }
    async getAllPositivePhrases(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPositivePhrases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPositivePhrases();
            return result;
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getMonthlyBreakdown(arg0: string, arg1: bigint): Promise<MonthlyBreakdown> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyBreakdown(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyBreakdown(arg0, arg1);
            return result;
        }
    }
    async getMonthlySummary(arg0: string, arg1: bigint): Promise<MonthlySummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySummary(arg0, arg1);
                return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySummary(arg0, arg1);
            return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
        }
    }
    async getOtrosEntries(arg0: string): Promise<Array<OtrosEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOtrosEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOtrosEntries(arg0);
            return result;
        }
    }
    async getRandomPositivePhrase(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomPositivePhrase();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomPositivePhrase();
            return result;
        }
    }
    async getTripCategories(arg0: string): Promise<Array<TripCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripCategories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripCategories(arg0);
            return result;
        }
    }
    async getTripRecords(arg0: string): Promise<Array<TripRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTripRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTripRecords(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n2(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n2(this.uploadFile, this.downloadFile, result);
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async saveMonthlySummary(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMonthlySummary(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMonthlySummary(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateOtrosEntry(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOtrosEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOtrosEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateTripCategory(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTripCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTripCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTripRecord(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTripRecord(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTripRecord(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateUserProfile(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MonthlySummary]): MonthlySummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
